services:
  nre_ai:
    build: .
    container_name: nre
    stdin_open: true # Equivalent to -i
    tty: true # Equivalent to -t
    command: /bin/bash
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./submodules/:/app/submodules
      - ./scripts:/app/scripts
      - ./tests/:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./models:/app/models
      - ./logs:/app/logs

    environment:
      UV_LINK_MODE: copy
      CI: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
